### PR TITLE
simplify boolean logic

### PR DESCRIPTION
**Pull request by zaz**
Replace if statements with if-not statements that `continue` or `exit`.

### CODE REVIEW

**Comment by notpushkin** [comment]
Sorry for this taking so long, I thought I've already merged it!

**Comment by zaz** [comment]
No worries.  Thanks for merging!

**Comment by notpushkin** [comment]
@zaz I'm planning to release this under [Unlicense](http://unlicense.org/), would you have any problem with that?

**Comment by zaz** [comment]
@iamale: Sure.  No problem.

**Pull request merged**
